<?php

namespace AppBundle\Repository;

/**
 * PatronsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatronsRepository extends \Doctrine\ORM\EntityRepository
{
}
